server:
  port: 8762 # 端口号
spring:
  application:
    name: eureka-server # 应用名称（集群下相同）
  # 安全认证
  security:
    user:
      name: root
      password: 123456

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: eureka02          # 主机名，不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true     # 是否使用IP地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #更改主机的实例ID
  client:
    # 设置服务注册中心地址，指向另一个注册中心
    service-url:                # 注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8761/eureka/

