server:
  port: 9091
  compression:
    enabled: true # 是否开启压缩
    mime-types: application/json,application/xml,text/html,text/xml,text/plain # 配置压缩支持的 MIME TYPE
spring:
  application:
    name: service-consumer  # 应用名称（集群下相同）

# 配置 Eureka Server
eureka:
  client:
    register-with-eureka: false   # 是否将自己注册到注册中心，默认为true
    register-fetch-interval-seconds: 10 # 表示 Eureka Client 间隔多久去服务器拉取注册信息，默认为30秒
    service-url:                # 注册中心对外暴露的注册地址
      defaultZone: http://root:123456@localhost:8761/eureka/,http://root:123456@localhost:8762/eureka/

feign:
  httpclient:
    enabled: true # 开启 httpclient

#ribbon:
#  ConnectTimeout: 5000 # 请求连接的超时时间，默认的时间为 1 秒
#  ReadTimeout: 5000 # 请求处理的超时时间

## 负载均衡策略
## service-provider 为调用的服务名称（注册中心中定义的名称）
#service-provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 此处设置随机策略
#    OkToRetryOnAllOperations: true      # 对所有的请求都进行
#    MaxAutoRetries: 2                   # 对当前实例的重试次数
#    MaxAutoRetriesNextServer: 0         # 切换实例的重试次数
#    ConnectTimeout: 3000                # 请求连接的超时时间
#    ReadTimeout: 3000                   # 请求处理的超时时间